### ISSUE TITLE
Crash On Startup

### ISSUE THREAD

**Issue by Storm99999** [Tamely/SaturnSwapper#105] opened 2024-02-12 23:48 UTC
Steps to reproduce:
  - install, extract
  - open

Opens fine, parses game files as expected, completes as usual, and on the Home Page it closes.
Antivirus off.

**Comment by auccs** [comment] 2024-02-14 03:08
read announcements in the discord

**Comment by Storm99999** [comment] 2024-02-17 23:20
I'm not verified in it

**Comment by auccs** [comment] 2024-02-17 23:26
so verify...

**Comment by Storm99999** [comment] 2024-02-24 02:45
restorecord is selling their user db. not doing that

**Comment by Tamely** [comment] 2024-02-24 02:50
@Storm99999 Proof? I don't see any proof of that whatsoever. There's proof there was a marketplace for server owners selling their members, but nothing about the owner selling the user database. That wouldn't even matter though as all evidence of anything shady was dropped after the server owners got ownership of the bots instead of one main bot.

**Comment by Smooktober** [comment] 2024-02-26 21:31
not my place to ask abt it but a site recently came up which let users search for peoples ip's using their discord id, and it was confirmed to have used restorecord's db for it, also the owner of that site was an admin for restorecord's telegram and had close connection with the owner. so either he accessed it without owner knowing or it was a mutual agreement, either way its shady asf

https://www.youtube.com/watch?v=d0h4QPqAwss - vid abt it
https://inf0sec.net/ - the site they sold the ip service on

**Comment by auccs** [comment] 2024-02-26 21:32
the video legit says it was fixed

**Comment by Smooktober** [comment] 2024-02-26 21:34
ik, but it also said the sites still work, so they couldve downloaded db or regained access

**Comment by auccs** [comment] 2024-02-26 21:36
no proof of that but ur ip has def changed since you joined saturn and no one would leak ur IP unless they're targeting specifically u.

**Comment by Tamely** [comment] 2024-02-26 21:39
Yes, RestoreCord gets your IP. No, that's not an issue bc the pros outweigh the cons.

Pros:
- I can ban people from the server and prevent them from joining with VPNs/Proxies/wtv
- I can restore everyone in the case of a ban (which has happened multiple times)
- It blocks bots from joining
- Makes raids harder

Cons:
- Your IP gets stored in a database (the IP doesn't get updated which means - if it changes [most IPs change every 2 weeks] - it has outdated info completely unrelated to you. if it hasn't changed, turn your router off for 15 minutes and it will)

Even with that said, I'm already moving to a different platform when SaturnV3 releases.

**Comment by Smooktober** [comment] 2024-02-26 21:42
yea im not tryna tell yall what to do just wanted to bring it to your attention

**Comment by Storm99999** [comment] 2024-02-27 11:50
The guy that was using the restorecord db for his searchup site is still an admin of restorecord. xenos (the owner of restorecord), is in the doxbin community. Not someone i would trust having a database of users.

**Closed** 2024-08-05 21:01 UTC
